[tools]
"aqua:neovim/neovim" = "latest"
"github:tomrford/grepo" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
atuin = "latest"
bat = "latest"
bazelisk = "latest"
bun = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
lazygit = "latest"
node = "24"
pnpm = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
zoxide = "latest"
rust = "latest"
deno = "latest"

[env]
EDITOR = "nvim"
PAGER = "less -FirSwX"

[settings]
dotfiles.root = "~/.config/mise"
dotfiles.default_mode = "symlink"
minimum_release_age_excludes = ["github:tomrford/grepo"]

[dotfiles]
"~/.agents/skills" = {}
"~/.codex/AGENTS.md" = {}
